import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.pricing': 'Pricing',
    'nav.sizes': 'Dumpster Sizes',
    'nav.areas': 'Service Areas',
    'nav.materials': 'Materials Allowed',
    'nav.contractors': 'Contractors',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.orderNow': 'Order Now',
    'nav.getQuote': 'Get Instant Quote',
    
    // Hero
    'hero.title': 'Fast & Reliable Dumpster Rentals',
    'hero.subtitle': 'in Northern California',
    'hero.description': 'Instant estimates. Contractor-friendly. Additional fees may apply for overages.',
    'hero.cta.quote': 'Get Instant Quote',
    'hero.cta.call': 'Call Now',
    'hero.cta.order': 'Order Now',
    'hero.spanish': 'Hablamos Español',
    'hero.trust': 'Google Guaranteed',
    'hero.benefit.sameDay': 'Same-Day Delivery',
    'hero.benefit.transparent': 'Transparent Pricing',
    'hero.benefit.onTime': 'Reliable On-Time Service',
    'hero.stats.counties': 'Counties Served',
    'hero.stats.customers': 'Happy Customers',
    'hero.stats.delivery': 'Delivery',
    
    // Features
    'features.sameDay': 'Same-Day Delivery',
    'features.sameDayDesc': 'Need a dumpster today? We deliver.',
    'features.transparent': 'Transparent Pricing',
    'features.transparentDesc': 'No hidden fees. Ever.',
    'features.onTime': 'On-Time Service',
    'features.onTimeDesc': 'We show up when we say we will.',
    'features.textUpdates': 'Text Updates',
    'features.textUpdatesDesc': 'Track your delivery via SMS.',
    'features.title': 'Why Choose Us?',
    'features.subtitle': 'Transparent pricing with no surprises • Contractor & bulk accounts available • Reliable delivery and pickup • Multiple service areas across Northern California • Real equipment. Real local team.',
    'features.googleGuaranteed': 'Google Guaranteed',
    'features.googleGuaranteedDesc': 'Protected by Google Local Services.',
    'features.ecoFriendly': 'Eco-Friendly',
    'features.ecoFriendlyDesc': 'We recycle and dispose responsibly.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Renting a dumpster is easy. Four simple steps from quote to haul-away.',
    'howItWorks.step1.title': 'Get a Quote',
    'howItWorks.step1.description': 'Tell us your project type, location, and preferred size. Get instant pricing in seconds.',
    'howItWorks.step2.title': 'We Deliver',
    'howItWorks.step2.description': 'Same-day or scheduled delivery. We place the dumpster exactly where you need it.',
    'howItWorks.step3.title': 'Fill It Up',
    'howItWorks.step3.description': 'Take your time—standard rental is 7 days. Load at your own pace.',
    'howItWorks.step4.title': 'We Haul Away',
    'howItWorks.step4.description': 'Call or text when ready. We pick up within 1-3 business days.',
    'howItWorks.cta': 'Get Your Instant Quote',
    
    // CTA Section
    'ctaSection.title': 'Ready to Get Started?',
    'ctaSection.subtitle': 'Book your dumpster in minutes. Same-day delivery available for orders placed before noon.',
    
    // CTA
    'cta.call': 'Call',
    'cta.text': 'Text',
    'cta.quote': 'Quote',
    'cta.order': 'Order Now',
    
    // Forms
    'form.zip': 'ZIP Code',
    'form.size': 'Dumpster Size',
    'form.material': 'Material Type',
    'form.deliveryDate': 'Delivery Date',
    'form.rentalDays': 'Rental Days',
    'form.notes': 'Delivery Notes',
    'form.name': 'Full Name',
    'form.email': 'Email',
    'form.phone': 'Phone Number',
    'form.address': 'Delivery Address',
    'form.submit': 'Get My Estimate',
    'form.submitting': 'Getting Estimate...',
    
    // Sizes
    'sizes.title': 'Dumpster Sizes',
    'sizes.subtitle': 'From small cleanouts to major construction projects. Find the perfect size for your needs.',
    'sizes.perfectFor': 'Perfect for:',
    'sizes.dimensions': 'Dimensions:',
    'sizes.choose': 'Choose This Size',
    'sizes.yards': 'Yard',
    'sizes.from': 'From',
    'sizes.viewAll': 'View All Sizes',
    
    // Footer
    'footer.company': 'Calsan Dumpsters Pro',
    'footer.tagline': 'Your trusted dumpster rental partner in the SF Bay Area.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact Us',
    'footer.hours': 'Customer Service: Mon-Sun 6AM-9PM',
    'footer.operations': 'Delivery: Mon-Fri by time window',
    'footer.weekend': 'Weekend service by special request',
    'footer.afterHours': 'After-hours messages answered next business window',
    'footer.rights': 'All rights reserved.',
    
    // Trust
    'trust.title': 'Why Choose Us',
    'trust.guarantee': 'Google Guarantee',
    'trust.guaranteeDesc': 'Protected by Google Local Services. If you\'re not satisfied, Google may refund up to $2,000.',
    
    // Reviews
    'reviews.title': 'What Our Customers Say',
    'reviews.leave': 'Leave a Review',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about our dumpster rental services.',
    'faq.moreQuestions': 'Still have questions?',
    'faq.callUs': 'Call us at',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to help. Reach out anytime.',
    'contact.phone': 'Phone (Sales)',
    'contact.support': 'Customer Support',
    'contact.email': 'Email',
    'contact.address': 'Address',

    // Capacity Guide
    'capacity.badge': 'Real-World Capacity Guide',
    'capacity.title': 'How Much Fits in Each Dumpster?',
    'capacity.subtitle': 'These are real-world estimates based on common projects in the Bay Area. Actual capacity varies by material type, how it\'s loaded, and moisture weight.',
    'capacity.ctaZip': 'Get Instant Quote by ZIP',
    'capacity.pickupTitle': 'Pickup Truck Loads',
    'capacity.pickupSubtitle': 'How many standard 6-ft bed pickup loads fit in each dumpster',
    'capacity.pickupNote': 'Pickup load estimates assume a standard 6-ft bed pickup, loaded to the top of the bed.',
    'capacity.homeownerTitle': 'Common Homeowner Scenarios',
    'capacity.homeownerSubtitle': 'Estimated dumpster sizes for typical home projects',
    'capacity.contractorTitle': 'Contractor Scenarios',
    'capacity.contractorSubtitle': 'Professional project estimates with weight considerations',
    'capacity.businessTitle': 'Business Scenarios',
    'capacity.businessSubtitle': 'Commercial and property management projects',
    'capacity.concreteTitle': 'Concrete & Heavy Material Quick Math',
    'capacity.concreteSubtitle': 'Weight-limited capacity for slabs and heavy loads',
    'capacity.concreteWeightRef': 'Concrete Weight Reference',
    'capacity.slab4in': '4-inch slab',
    'capacity.slab4inWeight': '≈ ~50 lb per square foot (estimate)',
    'capacity.slab6in': '6-inch slab',
    'capacity.slab6inWeight': '≈ ~75 lb per square foot (estimate)',
    'capacity.practicalCapacity': 'Practical Capacity by Dumpster',
    'capacity.size': 'Size',
    'capacity.demoTitle': 'House Demolition Estimates',
    'capacity.demoSubtitle': 'For a typical 1,200 sq ft Bay Area house demolition:',
    'capacity.demoWoodFrame': 'Wood-frame demo (no foundation)',
    'capacity.demoWoodFrameWeight': 'Roughly ~30–60 tons (range)',
    'capacity.demoWithFoundation': 'With foundation/concrete included',
    'capacity.demoWithFoundationWeight': 'Roughly ~60–120 tons (range)',
    'capacity.demoNote': 'Actual weight varies heavily by materials, plaster vs drywall, roof layers, and foundation type. Large demo projects typically require multiple dumpster pulls.',
    'capacity.heavyDisclaimer': 'Heavy Material Disclaimer',
     'capacity.heavyDisclaimerText': 'Concrete is weight-limited. These ranges depend on thickness, rebar, moisture, and access. We\'ll recommend the safest option for your project. Heavy material dumpsters (5/8/10yd) are',
     'capacity.flatFeeNote': ' FLAT FEE—disposal included with no extra weight charges.',
     'capacity.pricingRulesTitle': 'Disposal & Pricing Rules',
     'capacity.heavyMaterialsTitle': 'Heavy Materials (5/8/10 yd)',
     'capacity.heavyMaterialsDesc': 'FLAT FEE pricing. Disposal included with no extra weight charges. Concrete, dirt, rock, brick, asphalt only—no mixing with trash.',
    'capacity.mixed610Title': 'General Debris (All Sizes)',
    'capacity.mixed610Desc': 'General debris dumpsters include base tonnage by size. Any weight beyond the included amount is billed at $165 per ton, based on scale ticket.',
    'capacity.mixed20Title': 'Overage Rules',
    'capacity.mixed20Desc': 'We weigh every load at the disposal facility. You receive a scale ticket showing actual weight, and any overage is billed at $165/ton.',
    'capacity.keepBelowRim': 'Keep loads below rim',
    'capacity.keepBelowRimDesc': 'Materials must not extend above the top of the dumpster walls. Do not mix prohibited materials.',
    'capacity.ctaTitle': 'Not Sure What Size You Need?',
    'capacity.ctaSubtitle': 'Enter your ZIP and material type—we\'ll recommend the safest, most cost-effective option.',
    'capacity.textUs': 'Text Us',
    'capacity.callNow': 'Call Now',
    'capacity.yard': 'yard',
    'capacity.loads': 'loads',
    'capacity.typicalUse': 'Typical Use',
    'capacity.dimensions': 'Dimensions',
    'capacity.dumpsterSize': 'Dumpster Size',
    'capacity.pickupLoads': 'Pickup Loads',
    'capacity.askContractor': 'Ask about contractor program',

    // Scenario cards
    'scenario.garage': 'Garage Cleanout (1-2 Car)',
    'scenario.garageWhy': 'Years of accumulated items, old furniture, and boxes typically fill 10-20 cubic yards.',
    'scenario.garageWeight': 'Light materials—standard pricing applies.',
    'scenario.bathroom': 'Bathroom Remodel',
    'scenario.bathroomWhy': 'Demolition debris including tile, fixtures, drywall, and cabinetry.',
    'scenario.bathroomWeight': 'Tile and fixtures add weight. Dispose of old toilets and sinks.',
    'scenario.kitchen': 'Kitchen Remodel',
    'scenario.kitchenWhy': 'Cabinets, countertops, flooring, appliances, and drywall require more space.',
    'scenario.kitchenWeight': 'Countertops (granite/marble) are heavy—separate if possible.',
    'scenario.deck': 'Small Deck Removal',
    'scenario.deckWhy': 'Treated lumber, railings, and hardware from a typical residential deck.',
    'scenario.deckWeight': 'Treated wood is heavier when wet.',
    'scenario.roof': 'Roof Tear-Off (Single Layer)',
    'scenario.roofWhy': 'Shingles are heavy. A typical home (~15-20 squares) fills 10-20 yards.',
    'scenario.roofWeight': 'Roofing is weight-limited. Ask about number of "squares" (100 sf each).',
    'scenario.yard': 'Yard Cleanup / Green Waste',
    'scenario.yardWhy': 'Branches, brush, leaves, and debris from landscaping projects.',
    'scenario.yardWeight': 'Green waste is light when dry, heavy when wet.',
    'scenario.smallDemo': 'Small Demo (1 Room + Drywall/Wood)',
    'scenario.smallDemoWhy': 'Single room demolition with drywall, framing lumber, and finishes.',
    'scenario.smallDemoWeight': 'Standard mixed debris pricing.',
    'scenario.fullRemodel': 'Full Remodel (Multiple Rooms)',
    'scenario.fullRemodelWhy': 'Multi-room renovation with cabinets, flooring, fixtures, and framing.',
    'scenario.fullRemodelWeight': 'May need multiple pulls for large projects.',
    'scenario.lightDemo': 'Light Demo / Renovation + Framing',
    'scenario.lightDemoWhy': 'Tenant improvements with significant lumber and drywall.',
    'scenario.lightDemoWeight': 'Lumber is bulky but relatively light.',
    'scenario.commercial': 'Commercial Cleanout / TI',
    'scenario.commercialWhy': 'Office buildouts, retail spaces, and warehouse cleanouts require maximum capacity.',
    'scenario.commercialWeight': 'Watch for weight limits on mixed loads.',
    'scenario.concrete': 'Concrete / Dirt (HEAVY)',
    'scenario.concreteWhy': 'FLAT FEE pricing for pure heavy material loads. Weight not a concern.',
    'scenario.concreteWeight': 'HEAVY ONLY: Must be clean loads (no trash). 5/8/10 yard ONLY.',
    'scenario.retail': 'Retail / Office Cleanout',
    'scenario.retailWhy': 'Furniture, fixtures, equipment, and general office waste.',
    'scenario.retailWeight': 'Metal fixtures and equipment add weight.',
    'scenario.property': 'Property Management Turnover',
    'scenario.propertyWhy': 'Unit turnovers with furniture, appliances, and renovation debris.',
    'scenario.propertyWeight': 'Multiple turnovers may need scheduled pickups.',
    'scenario.ongoing': 'Ongoing Construction Projects',
    'scenario.ongoingWhy': 'Continuous debris from active job sites.',
    'scenario.ongoingWeight': 'Ask about contractor program for volume discounts.',

    // Pickup truck notes
    'pickup.note6': 'Small cleanouts',
    'pickup.note8': 'Medium projects',
    'pickup.note10': 'Room renovations',
    'pickup.note20': 'Larger remodels',
    'pickup.note30': 'Major renovations',
    'pickup.note40': 'Commercial scale',
    'pickup.note50': 'Maximum capacity',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.pricing': 'Precios',
    'nav.sizes': 'Tamaños',
    'nav.areas': 'Áreas de Servicio',
    'nav.materials': 'Materiales',
    'nav.contractors': 'Contratistas',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'nav.orderNow': 'Ordenar Ahora',
    'nav.getQuote': 'Cotización Gratis',
    
    // Hero
    'hero.title': 'Alquiler de Contenedores Rápido y Confiable',
    'hero.subtitle': 'en el Norte de California',
    'hero.description': 'Precios instantáneos. Ideal para contratistas. Sin cargos ocultos.',
    'hero.cta.quote': 'Cotización Gratis',
    'hero.cta.call': 'Llamar Ahora',
    'hero.cta.order': 'Ordenar Ahora',
    'hero.spanish': 'Hablamos Español',
    'hero.trust': 'Garantizado por Google',
    'hero.benefit.sameDay': 'Entrega el Mismo Día',
    'hero.benefit.transparent': 'Precios Transparentes',
    'hero.benefit.onTime': 'Servicio Puntual Confiable',
    'hero.stats.counties': 'Condados',
    'hero.stats.customers': 'Clientes Felices',
    'hero.stats.delivery': 'Entrega',
    
    // Features
    'features.sameDay': 'Entrega el Mismo Día',
    'features.sameDayDesc': '¿Necesita un contenedor hoy? Lo entregamos.',
    'features.transparent': 'Precios Transparentes',
    'features.transparentDesc': 'Sin cargos ocultos. Nunca.',
    'features.onTime': 'Servicio Puntual',
    'features.onTimeDesc': 'Llegamos cuando decimos.',
    'features.textUpdates': 'Actualizaciones por Texto',
    'features.textUpdatesDesc': 'Siga su entrega por SMS.',
    'features.title': '¿Por Qué Elegirnos?',
    'features.subtitle': 'Precios transparentes sin sorpresas • Cuentas para contratistas y volumen disponibles • Entrega y recogida confiables • Múltiples áreas de servicio en el norte de California • Equipo real. Equipo local.',
    'features.googleGuaranteed': 'Garantizado por Google',
    'features.googleGuaranteedDesc': 'Protegido por Servicios Locales de Google.',
    'features.ecoFriendly': 'Ecológico',
    'features.ecoFriendlyDesc': 'Reciclamos y desechamos responsablemente.',
    
    // How It Works
    'howItWorks.title': 'Cómo Funciona',
    'howItWorks.subtitle': 'Alquilar un contenedor es fácil. Cuatro pasos simples desde la cotización hasta el retiro.',
    'howItWorks.step1.title': 'Obtén una Cotización',
    'howItWorks.step1.description': 'Cuéntanos tu proyecto, ubicación y tamaño preferido. Obtén precios al instante.',
    'howItWorks.step2.title': 'Lo Entregamos',
    'howItWorks.step2.description': 'Entrega el mismo día o programada. Colocamos el contenedor donde lo necesites.',
    'howItWorks.step3.title': 'Llénalo',
    'howItWorks.step3.description': 'Toma tu tiempo—el alquiler estándar es de 7 días. Carga a tu propio ritmo.',
    'howItWorks.step4.title': 'Lo Retiramos',
    'howItWorks.step4.description': 'Llama o envía un mensaje cuando estés listo. Recogemos en 1-3 días hábiles.',
    'howItWorks.cta': 'Obtén Tu Cotización Gratis',
    
    // CTA Section
    'ctaSection.title': '¿Listo para Empezar?',
    'ctaSection.subtitle': 'Reserva tu contenedor en minutos. Entrega el mismo día para pedidos antes del mediodía.',
    
    // CTA
    'cta.call': 'Llamar',
    'cta.text': 'Texto',
    'cta.quote': 'Cotizar',
    'cta.order': 'Ordenar Ahora',
    
    // Forms
    'form.zip': 'Código Postal',
    'form.size': 'Tamaño del Contenedor',
    'form.material': 'Tipo de Material',
    'form.deliveryDate': 'Fecha de Entrega',
    'form.rentalDays': 'Días de Alquiler',
    'form.notes': 'Notas de Entrega',
    'form.name': 'Nombre Completo',
    'form.email': 'Correo Electrónico',
    'form.phone': 'Número de Teléfono',
    'form.address': 'Dirección de Entrega',
    'form.submit': 'Obtener Estimado',
    'form.submitting': 'Obteniendo Estimado...',
    
    // Sizes
    'sizes.title': 'Tamaños de Contenedores',
    'sizes.subtitle': 'Desde limpiezas pequeñas hasta grandes proyectos de construcción. Encuentra el tamaño perfecto.',
    'sizes.perfectFor': 'Perfecto para:',
    'sizes.dimensions': 'Dimensiones:',
    'sizes.choose': 'Elegir Este Tamaño',
    'sizes.yards': 'Yardas',
    'sizes.from': 'Desde',
    'sizes.viewAll': 'Ver Todos los Tamaños',
    
    // Footer
    'footer.company': 'Calsan Dumpsters Pro',
    'footer.tagline': 'Su socio confiable de alquiler de contenedores en el Área de la Bahía.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.contact': 'Contáctenos',
    'footer.hours': 'Servicio al Cliente: Lun-Dom 6AM-9PM',
    'footer.operations': 'Entregas: Lun-Vie por ventana de tiempo',
    'footer.weekend': 'Servicio de fin de semana por solicitud especial',
    'footer.afterHours': 'Mensajes fuera de horario respondidos en la próxima ventana',
    'footer.rights': 'Todos los derechos reservados.',
    
    // Trust
    'trust.title': 'Por Qué Elegirnos',
    'trust.guarantee': 'Garantía de Google',
    'trust.guaranteeDesc': 'Protegido por Servicios Locales de Google. Si no está satisfecho, Google puede reembolsar hasta $2,000.',
    
    // Reviews
    'reviews.title': 'Lo Que Dicen Nuestros Clientes',
    'reviews.leave': 'Dejar una Reseña',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Todo lo que necesita saber sobre nuestros servicios de alquiler de contenedores.',
    'faq.moreQuestions': '¿Aún tiene preguntas?',
    'faq.callUs': 'Llámenos al',
    
    // Contact
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Estamos aquí para ayudar. Comuníquese en cualquier momento.',
    'contact.phone': 'Teléfono (Ventas)',
    'contact.support': 'Soporte al Cliente',
    'contact.email': 'Correo',
    'contact.address': 'Dirección',

    // Capacity Guide
    'capacity.badge': 'Guía de Capacidad Real',
    'capacity.title': '¿Cuánto Cabe en Cada Dumpster?',
    'capacity.subtitle': 'Estos son estimados reales basados en proyectos comunes en el Área de la Bahía. La capacidad real varía según el material, la forma de carga y la humedad.',
    'capacity.ctaZip': 'Cotizar por Código Postal',
    'capacity.pickupTitle': 'Equivalente en Cargas de Pickup',
    'capacity.pickupSubtitle': 'Cuántas cargas de camioneta estándar (caja de 6 pies) caben en cada dumpster',
    'capacity.pickupNote': 'Estimados basados en camioneta estándar con caja de 6 pies, cargada al nivel del borde.',
    'capacity.homeownerTitle': 'Escenarios Comunes para Propietarios',
    'capacity.homeownerSubtitle': 'Tamaños estimados de dumpster para proyectos típicos del hogar',
    'capacity.contractorTitle': 'Escenarios para Contratistas',
    'capacity.contractorSubtitle': 'Estimaciones profesionales con consideraciones de peso',
    'capacity.businessTitle': 'Escenarios Comerciales',
    'capacity.businessSubtitle': 'Proyectos comerciales y de administración de propiedades',
    'capacity.concreteTitle': 'Guía Rápida de Concreto y Materiales Pesados',
    'capacity.concreteSubtitle': 'Capacidad limitada por peso para losas y cargas pesadas',
    'capacity.concreteWeightRef': 'Referencia de Peso del Concreto',
    'capacity.slab4in': 'Losa de 4 pulgadas',
    'capacity.slab4inWeight': '≈ ~50 lb por pie cuadrado (estimado)',
    'capacity.slab6in': 'Losa de 6 pulgadas',
    'capacity.slab6inWeight': '≈ ~75 lb por pie cuadrado (estimado)',
    'capacity.practicalCapacity': 'Capacidad Práctica por Dumpster',
    'capacity.size': 'Tamaño',
    'capacity.demoTitle': 'Estimados de Demolición de Casa',
    'capacity.demoSubtitle': 'Para una demolición típica de casa de 1,200 pies² en el Área de la Bahía:',
    'capacity.demoWoodFrame': 'Demolición de estructura de madera (sin cimiento)',
    'capacity.demoWoodFrameWeight': 'Aproximadamente ~30–60 toneladas',
    'capacity.demoWithFoundation': 'Con cimiento/concreto incluido',
    'capacity.demoWithFoundationWeight': 'Aproximadamente ~60–120 toneladas',
    'capacity.demoNote': 'El peso real varía mucho según los materiales, yeso vs paneles de yeso, capas del techo y tipo de cimiento. Proyectos grandes de demolición típicamente requieren múltiples retiros.',
    'capacity.heavyDisclaimer': 'Aviso sobre Materiales Pesados',
    'capacity.heavyDisclaimerText': 'El concreto está limitado por peso. Estos rangos dependen del espesor, varilla, humedad y acceso. Recomendaremos la opción más segura para tu proyecto. Los dumpsters para material pesado (6/8/10yd) son',
    'capacity.flatFeeNote': ' PRECIO FIJO—disposición incluida sin cargos extra por peso.',
    'capacity.pricingRulesTitle': 'Reglas de Disposición y Precios',
    'capacity.heavyMaterialsTitle': 'Materiales Pesados (6/8/10 yd)',
    'capacity.heavyMaterialsDesc': 'PRECIO FIJO. Disposición incluida sin cargos extra por peso. Solo concreto, tierra, piedra, ladrillo, asfalto—no mezclar con basura.',
    'capacity.mixed610Title': 'Escombro Mixto (6/8/10 yd)',
    'capacity.mixed610Desc': 'Excedente cobrado a $30 por yarda adicional. Facturación basada en capacidad para cargas mixtas pequeñas.',
    'capacity.mixed20Title': 'Escombro Mixto (20/30/40/50 yd)',
    'capacity.mixed20Desc': 'Toneladas incluidas por tamaño (2-5T). Excedente cobrado a $165/ton después del ticket de báscula.',
    'capacity.keepBelowRim': 'Mantener carga bajo el borde',
    'capacity.keepBelowRimDesc': 'Los materiales no deben extenderse sobre las paredes del dumpster. No mezclar materiales prohibidos.',
    'capacity.ctaTitle': '¿No Estás Seguro del Tamaño?',
    'capacity.ctaSubtitle': 'Ingresa tu código postal y tipo de material—te recomendaremos la opción más segura y económica.',
    'capacity.textUs': 'Enviar Mensaje',
    'capacity.callNow': 'Llamar Ahora',
    'capacity.yard': 'yardas',
    'capacity.loads': 'cargas',
    'capacity.typicalUse': 'Uso Típico',
    'capacity.dimensions': 'Dimensiones',
    'capacity.dumpsterSize': 'Tamaño de Dumpster',
    'capacity.pickupLoads': 'Cargas de Pickup',
    'capacity.askContractor': 'Pregunta por el programa para contratistas',

    // Scenario cards
    'scenario.garage': 'Limpieza de Garage (1-2 Autos)',
    'scenario.garageWhy': 'Años de artículos acumulados, muebles viejos y cajas típicamente llenan 10-20 yardas cúbicas.',
    'scenario.garageWeight': 'Materiales ligeros—aplica precio estándar.',
    'scenario.bathroom': 'Remodelación de Baño',
    'scenario.bathroomWhy': 'Escombros de demolición incluyendo azulejo, accesorios, paneles de yeso y gabinetes.',
    'scenario.bathroomWeight': 'Azulejo y accesorios añaden peso. Deseche inodoros y lavabos viejos.',
    'scenario.kitchen': 'Remodelación de Cocina',
    'scenario.kitchenWhy': 'Gabinetes, encimeras, pisos, electrodomésticos y paneles de yeso requieren más espacio.',
    'scenario.kitchenWeight': 'Encimeras (granito/mármol) son pesadas—separar si es posible.',
    'scenario.deck': 'Remoción de Deck Pequeño',
    'scenario.deckWhy': 'Madera tratada, barandales y herrajes de un deck residencial típico.',
    'scenario.deckWeight': 'La madera tratada es más pesada cuando está mojada.',
    'scenario.roof': 'Retiro de Techo (Una Capa)',
    'scenario.roofWhy': 'Las tejas son pesadas. Una casa típica (~15-20 cuadros) llena 10-20 yardas.',
    'scenario.roofWeight': 'Techado está limitado por peso. Pregunte sobre número de "cuadros" (100 pies² cada uno).',
    'scenario.yard': 'Limpieza de Jardín / Green Waste',
    'scenario.yardWhy': 'Ramas, arbustos, hojas y escombros de proyectos de jardinería.',
    'scenario.yardWeight': 'El green waste es ligero cuando está seco, pesado cuando está mojado.',
    'scenario.smallDemo': 'Demolición Pequeña (1 Cuarto)',
    'scenario.smallDemoWhy': 'Demolición de un cuarto con paneles de yeso, madera estructural y acabados.',
    'scenario.smallDemoWeight': 'Precio estándar para escombro mixto.',
    'scenario.fullRemodel': 'Remodelación Completa (Múltiples Cuartos)',
    'scenario.fullRemodelWhy': 'Renovación de múltiples cuartos con gabinetes, pisos, accesorios y estructura.',
    'scenario.fullRemodelWeight': 'Puede necesitar múltiples retiros para proyectos grandes.',
    'scenario.lightDemo': 'Demo Ligera / Renovación + Estructura',
    'scenario.lightDemoWhy': 'Mejoras para inquilinos con madera estructural significativa y paneles de yeso.',
    'scenario.lightDemoWeight': 'La madera es voluminosa pero relativamente ligera.',
    'scenario.commercial': 'Limpieza Comercial / TI',
    'scenario.commercialWhy': 'Construcciones de oficinas, espacios comerciales y limpiezas de bodegas requieren capacidad máxima.',
    'scenario.commercialWeight': 'Cuidado con los límites de peso en cargas mixtas.',
    'scenario.concrete': 'Concreto / Tierra (PESADO)',
    'scenario.concreteWhy': 'PRECIO FIJO para cargas de material pesado puro. El peso no es preocupación.',
    'scenario.concreteWeight': 'SOLO PESADO: Deben ser cargas limpias (sin basura). SOLO 6/8/10 yardas.',
    'scenario.retail': 'Limpieza de Local / Oficina',
    'scenario.retailWhy': 'Muebles, accesorios, equipo y basura general de oficina.',
    'scenario.retailWeight': 'Accesorios y equipo de metal añaden peso.',
    'scenario.property': 'Cambio de Inquilino (Property Management)',
    'scenario.propertyWhy': 'Cambios de unidades con muebles, electrodomésticos y escombros de renovación.',
    'scenario.propertyWeight': 'Múltiples cambios pueden necesitar retiros programados.',
    'scenario.ongoing': 'Proyectos de Construcción Continuos',
    'scenario.ongoingWhy': 'Escombro continuo de sitios de trabajo activos.',
    'scenario.ongoingWeight': 'Pregunta por el programa de contratistas para descuentos por volumen.',

    // Pickup truck notes
    'pickup.note6': 'Limpiezas pequeñas',
    'pickup.note8': 'Proyectos medianos',
    'pickup.note10': 'Renovaciones de cuartos',
    'pickup.note20': 'Remodelaciones grandes',
    'pickup.note30': 'Renovaciones mayores',
    'pickup.note40': 'Escala comercial',
    'pickup.note50': 'Capacidad máxima',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
